logging:
  level: INFO
  loggers:
    com.uwefuchs.demo.goeuro.dropwizard: DEBUG
    
server:
  type: simple
  applicationContextPath: /
  connector:
    type: http
    port: 8080
    
pathname: C:/sdd/demos_material/busroutes.dat
